import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {

  data = {
    "en": {
        appName: "Content Mangement System",
        Dashboard: "Dashboard",
        Users: "Users",
        Roles: "Roles",
        Faqs: "Faqs",
        Menus: "Menus",
        Pages: "Pages",
        Images: "Images",
        Settings: "Settings",
        Carousels: "Carousels",
        Dictionaries: "Dictionaries",
        welcomeTo: "Welcome to",
        welcomeText1: "powerfull tool for creating various elements",
        welcomeText2: "Here are modules that you have access to (specific actions depends on your roles):",
        UsersListNav: "Users list",
        UsersAddNav: "Add new user",
        RolesListNav: "Roles list",
        FaqsListNav: "Faqs list",
        FaqsAddNav: "Add new faq",
        MenusListNav: "Menus list",
        MenusAddNav: "Add new menu",
        PagesListNav: "Pages list",
        PagesAddNav: "Add new page",
        ImagesListNav: "Images list",
        ImagesAddNav: "Add new image",
        SettingsListNav: "Settings list",
        SettingsAddNav: "Add new setting",
        CarouselsListNav: "Carousels list",
        CarouselsAddNav: "Add new carousel",
        DictionariesListNav: "Dictionaries list",
        DictionariesAddNav: "Add new dictionary",
        location: "Location",
        locationUsers: "users",
        locationRegister: 'register',
        firstName: "First Name",
        lastName: "Last Name",
        email: "Email",
        status: "Status",
        password: 'Password',
        userItemsPerPage: "Users per page",
        filter: "Filter",
        newUserHeader: "Add new user",
        newUserEmailPlaceholder: "Type your email here",
        newUserFirstNamePlaceholder: "Type your first name here",
        newUserLastNamePlaceholder: "Type your lat name here",
        newUserPasswordPlaceholder: "Type your password here",
        selectRoles: "Select roles",
        register: "Register",
        user: "User",
        createdAt: "Created at",
        updatedAt: "Updated at",
        roles: "Roles",
        saveChanges: "Save changes",
        clearChanges: "Clear changes",
        removeUser: "Remove user",
        // fdf
        code: "Code",
        name: "Name",
        role: "Role",
        description: "description",
        typeCodeHere: "Type Code here",
        typeNameHere: "Type Name here",
        typeDescHere: "Type description here",
        add: "Add",
        elements: "elements",
        show: "show",
        hide: "hide",
        noElements: "This faq have no elements",
        remove: "Remove",
        page: "Page",
        general: "general",
        content: "content",
        styles: "styles",
        metaTags: "meta tags",
        chooseImage: "Choose image",
        settingType: "Setting type",
        typeValueHere: "Type value here",
        desktop: "Desktop",
        mobile: "Mobile",
        configuration: "Configuration"
    },
    "es":{
        appName: "Sistema de gestión de contenidos",
        Dashboard: "Tablero",
        Users: "Los usuarios",
        Roles: "Roles",
        Faqs: "Faqs",
        Menus: "Menús",
        Pages: "Páginas",
        Images: "Imágenes",
        Settings: "Configuraciones",
        Carousels: "Carruseles",
        Dictionaries: "Diccionarios",
        welcomeTo: "Bienvenido a",
        welcomeText1: "herramienta poderosa para crear varios elementos",
        welcomeText2: "Aquí hay módulos a los que tiene acceso (las acciones específicas dependen de sus roles):",
        UsersListNav: "Lista de usuarios",
        UsersAddNav: "Añadir nuevo usuario",
        RolesListNav: "Lista de roles",
        FaqsListNav: "Lista de preguntas frecuentes",
        FaqsAddNav: "Añadir nuevas preguntas frecuentes",
        MenusListNav: "Lista de menús",
        MenusAddNav: "Agregar nuevo menú",
        PagesListNav: "Lista de páginas",
        PagesAddNav: "Agregar nueva página",
        ImagesListNav: "Lista de imágenes",
        ImagesAddNav: "Agregar nueva imagen",
        SettingsListNav: "Lista de ajustes",
        SettingsAddNav: "AAgregar nueva configuración",
        CarouselsListNav: "Lista de carruseles",
        CarouselsAddNav: "Agregar nuevo carrusel",
        DictionariesListNav: "Lista de diccionarios",
        DictionariesAddNav: "Agregar nuevo diccionario",
        location: "Ubicación",
        locationUsers: "los usuarios",
        locationRegister: 'registrarse',
        firstName: "Nombre de pila",
        lastName: "Apellido",
        email: "Email",
        status: "Estado",
        password: 'contraseña',
        userItemsPerPage: "Usuarios por página",
        filter: "Filtrar",
        newUserHeader: "Añadir nuevo usuario",
        newUserEmailPlaceholder: "Escriba su correo electrónico aquí",
        newUserFirstNamePlaceholder: "Escribe tu nombre aquí",
        newUserLastNamePlaceholder: "Escriba su nombre de lat aquí",
        newUserPasswordPlaceholder: "Escriba su contraseña aquí",
        selectRoles: "Seleccionar roles",
        register: "Registrarse",
        user: "Usuario",
        createdAt: "Creado en",
        updatedAt: "Actualizado en",
        roles: "Roles",
        saveChanges: "Guardar cambios",
        clearChanges: "Cambios claros",
        removeUser: "Eliminar usuario",
        //
        code: "código",
        name: "nombre",
        role: "Papel",
        description: "descripción",
        typeCodeHere: "Escriba el código aquí",
        typeNameHere: "Escriba el nombre aquí",
        typeDescHere: "Escriba la descripción aquí",
        add: "añadir",
        elements: "elementos",
        show: "espectáculo",
        hide: "esconder",
        noElements: "Estas preguntas frecuentes no tienen elementos",
        remove: "Eliminar",
        page: "Pagina",
        general: "general",
        content: "contenido",
        styles: "estilos",
        metaTags: "metaetiquetas",
        chooseImage: "elegir imagen",
        settingType: "Tipo de ajuste",
        typeValueHere: "Escriba el valor aquí",
        desktop: "Escritorio",
        mobile: "Móvil",
        configuration: "Configuración"

      }
  }

  constructor() {
    if (!localStorage.getItem("languageCode")) {
      localStorage.setItem("languageCode", "en");
    }
   }

  getTranslation(code: string) {
    return this.data[localStorage.getItem("languageCode")][code];
  }

  changeLanguageCode(code: string) {
    localStorage.setItem("languageCode", code);
  }
}
